# Generated by Django 3.0.5 on 2020-04-02 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='group',
            name='description_html',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
